// ============================================================================
//
// Copyright (c) 2006-2015, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Big Data
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


package bigdata_project.stage_hosco_0_1;

import routines.Numeric;
import routines.DataOperation;
import routines.TalendDataGenerator;
import routines.TalendStringUtil;
import routines.TalendString;
import routines.StringHandling;
import routines.Relational;
import routines.TalendDate;
import routines.Mathematical;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;
 





@SuppressWarnings("unused")

/**
 * Job: Stage_Hosco Purpose: <br>
 * Description:  <br>
 * @author ray-hann06@hotmail.fr
 * @version 7.3.1.20200219_1130
 * @status 
 */
public class Stage_Hosco implements TalendJob {

protected static void logIgnoredError(String message, Throwable cause) {
       System.err.println(message);
       if (cause != null) {
               cause.printStackTrace();
       }

}


	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}
	
	private final static String defaultCharset = java.nio.charset.Charset.defaultCharset().name();

	
	private final static String utf8Charset = "UTF-8";
	//contains type for every context property
	public class PropertiesWithType extends java.util.Properties {
		private static final long serialVersionUID = 1L;
		private java.util.Map<String,String> propertyTypes = new java.util.HashMap<>();
		
		public PropertiesWithType(java.util.Properties properties){
			super(properties);
		}
		public PropertiesWithType(){
			super();
		}
		
		public void setContextType(String key, String type) {
			propertyTypes.put(key,type);
		}
	
		public String getContextType(String key) {
			return propertyTypes.get(key);
		}
	}
	
	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();
	// create application properties with default
	public class ContextProperties extends PropertiesWithType {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties){
			super(properties);
		}
		public ContextProperties(){
			super();
		}

		public void synchronizeContext(){
			
			if(HadoopHDFS_HoscoCo != null){
				
					this.setProperty("HadoopHDFS_HoscoCo", HadoopHDFS_HoscoCo.toString());
				
			}
			
			if(HadoopHDFS_HoscoHo != null){
				
					this.setProperty("HadoopHDFS_HoscoHo", HadoopHDFS_HoscoHo.toString());
				
			}
			
			if(HoscoStageCo != null){
				
					this.setProperty("HoscoStageCo", HoscoStageCo.toString());
				
			}
			
			if(HoscoStageHo != null){
				
					this.setProperty("HoscoStageHo", HoscoStageHo.toString());
				
			}
			
		}

public String HadoopHDFS_HoscoCo;
public String getHadoopHDFS_HoscoCo(){
	return this.HadoopHDFS_HoscoCo;
}
public String HadoopHDFS_HoscoHo;
public String getHadoopHDFS_HoscoHo(){
	return this.HadoopHDFS_HoscoHo;
}
public String HoscoStageCo;
public String getHoscoStageCo(){
	return this.HoscoStageCo;
}
public String HoscoStageHo;
public String getHoscoStageHo(){
	return this.HoscoStageHo;
}
	}
	protected ContextProperties context = new ContextProperties(); // will be instanciated by MS.
	public ContextProperties getContext() {
		return this.context;
	}
	private final String jobVersion = "0.1";
	private final String jobName = "Stage_Hosco";
	private final String projectName = "BIGDATA_PROJECT";
	public Integer errorCode = null;
	private String currentComponent = "";
	
		private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
        private final static java.util.Map<String, Object> junitGlobalMap = new java.util.HashMap<String, Object>();
	
		private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
		private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
		private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
		public  final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();
	

private RunStat runStat = new RunStat();

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";
	
	private final static String KEY_DB_DATASOURCES_RAW = "KEY_DB_DATASOURCES_RAW";

	public void setDataSources(java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources.entrySet()) {
			talendDataSources.put(dataSourceEntry.getKey(), new routines.system.TalendDataSource(dataSourceEntry.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap.put(KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
	}


private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(new java.io.BufferedOutputStream(baos));

public String getExceptionStackTrace() {
	if ("failure".equals(this.getStatus())) {
		errorMessagePS.flush();
		return baos.toString();
	}
	return null;
}

private Exception exception;

public Exception getException() {
	if ("failure".equals(this.getStatus())) {
		return this.exception;
	}
	return null;
}

private class TalendException extends Exception {

	private static final long serialVersionUID = 1L;

	private java.util.Map<String, Object> globalMap = null;
	private Exception e = null;
	private String currentComponent = null;
	private String virtualComponentName = null;
	
	public void setVirtualComponentName (String virtualComponentName){
		this.virtualComponentName = virtualComponentName;
	}

	private TalendException(Exception e, String errorComponent, final java.util.Map<String, Object> globalMap) {
		this.currentComponent= errorComponent;
		this.globalMap = globalMap;
		this.e = e;
	}

	public Exception getException() {
		return this.e;
	}

	public String getCurrentComponent() {
		return this.currentComponent;
	}

	
    public String getExceptionCauseMessage(Exception e){
        Throwable cause = e;
        String message = null;
        int i = 10;
        while (null != cause && 0 < i--) {
            message = cause.getMessage();
            if (null == message) {
                cause = cause.getCause();
            } else {
                break;          
            }
        }
        if (null == message) {
            message = e.getClass().getName();
        }   
        return message;
    }

	@Override
	public void printStackTrace() {
		if (!(e instanceof TalendException || e instanceof TDieException)) {
			if(virtualComponentName!=null && currentComponent.indexOf(virtualComponentName+"_")==0){
				globalMap.put(virtualComponentName+"_ERROR_MESSAGE",getExceptionCauseMessage(e));
			}
			globalMap.put(currentComponent+"_ERROR_MESSAGE",getExceptionCauseMessage(e));
			System.err.println("Exception in component " + currentComponent + " (" + jobName + ")");
		}
		if (!(e instanceof TDieException)) {
			if(e instanceof TalendException){
				e.printStackTrace();
			} else {
				e.printStackTrace();
				e.printStackTrace(errorMessagePS);
				Stage_Hosco.this.exception = e;
			}
		}
		if (!(e instanceof TalendException)) {
		try {
			for (java.lang.reflect.Method m : this.getClass().getEnclosingClass().getMethods()) {
				if (m.getName().compareTo(currentComponent + "_error") == 0) {
					m.invoke(Stage_Hosco.this, new Object[] { e , currentComponent, globalMap});
					break;
				}
			}

			if(!(e instanceof TDieException)){
			}
		} catch (Exception e) {
			this.e.printStackTrace();
		}
		}
	}
}

			public void tHiveConnection_1_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tHiveConnection_1_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tHiveRow_1_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tHiveRow_1_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tHiveCreateTable_1_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tHiveCreateTable_1_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tHiveLoad_1_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tHiveLoad_1_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tHiveRow_2_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tHiveRow_2_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tHiveCreateTable_2_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tHiveCreateTable_2_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tHiveLoad_2_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tHiveLoad_2_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tHiveConnection_1_onSubJobError(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {

resumeUtil.addLog("SYSTEM_LOG", "NODE:"+ errorComponent, "", Thread.currentThread().getId()+ "", "FATAL", "", exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception),"");

			}
			public void tHiveRow_1_onSubJobError(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {

resumeUtil.addLog("SYSTEM_LOG", "NODE:"+ errorComponent, "", Thread.currentThread().getId()+ "", "FATAL", "", exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception),"");

			}
			public void tHiveCreateTable_1_onSubJobError(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {

resumeUtil.addLog("SYSTEM_LOG", "NODE:"+ errorComponent, "", Thread.currentThread().getId()+ "", "FATAL", "", exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception),"");

			}
			public void tHiveLoad_1_onSubJobError(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {

resumeUtil.addLog("SYSTEM_LOG", "NODE:"+ errorComponent, "", Thread.currentThread().getId()+ "", "FATAL", "", exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception),"");

			}
			public void tHiveRow_2_onSubJobError(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {

resumeUtil.addLog("SYSTEM_LOG", "NODE:"+ errorComponent, "", Thread.currentThread().getId()+ "", "FATAL", "", exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception),"");

			}
			public void tHiveCreateTable_2_onSubJobError(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {

resumeUtil.addLog("SYSTEM_LOG", "NODE:"+ errorComponent, "", Thread.currentThread().getId()+ "", "FATAL", "", exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception),"");

			}
			public void tHiveLoad_2_onSubJobError(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {

resumeUtil.addLog("SYSTEM_LOG", "NODE:"+ errorComponent, "", Thread.currentThread().getId()+ "", "FATAL", "", exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception),"");

			}
	





public void tHiveConnection_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
	globalMap.put("tHiveConnection_1_SUBPROCESS_STATE", 0);

 final boolean execStat = this.execStat;
	
		String iterateId = "";
	
	
	String currentComponent = "";
	java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

	try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { //start the resume
				globalResumeTicket = true;



		


	
	/**
	 * [tHiveConnection_1 begin ] start
	 */

	

	
		
		ok_Hash.put("tHiveConnection_1", false);
		start_Hash.put("tHiveConnection_1", System.currentTimeMillis());
		
	
	currentComponent="tHiveConnection_1";

	
		int tos_count_tHiveConnection_1 = 0;
		

		
	

	
			globalMap.put("HADOOP_USER_NAME_tHiveConnection_1", System.getProperty("HADOOP_USER_NAME"));
			
							String url_tHiveConnection_1 = "jdbc:hive2://" + "group3.bigdata" + ":" + "10000" + "/" + "default";
				String additionalJdbcSettings_tHiveConnection_1 = "";
				if(!"".equals(additionalJdbcSettings_tHiveConnection_1.trim())) {
					if(!additionalJdbcSettings_tHiveConnection_1.startsWith(";")) {
						additionalJdbcSettings_tHiveConnection_1 = ";" + additionalJdbcSettings_tHiveConnection_1;
					}
					url_tHiveConnection_1 += additionalJdbcSettings_tHiveConnection_1;
				}
	String dbUser_tHiveConnection_1 = "cloudera";
	
	
		 
	final String decryptedPassword_tHiveConnection_1 = routines.system.PasswordEncryptUtil.decryptPassword("enc:routine.encryption.key.v1:QXVRWjNf4qh4NbAvv4EKjlhcTNP/EGd2I1RzDJP7dvJaBTlC");
		String dbPwd_tHiveConnection_1 = decryptedPassword_tHiveConnection_1;
	
	
	java.sql.Connection conn_tHiveConnection_1 = null;
	
		
			String driverClass_tHiveConnection_1 = "org.apache.hive.jdbc.HiveDriver";
			java.lang.Class jdbcclazz_tHiveConnection_1 = java.lang.Class.forName(driverClass_tHiveConnection_1);
			globalMap.put("driverClass_tHiveConnection_1", driverClass_tHiveConnection_1);
		
			conn_tHiveConnection_1 = java.sql.DriverManager.getConnection(url_tHiveConnection_1,dbUser_tHiveConnection_1,dbPwd_tHiveConnection_1);

		globalMap.put("conn_tHiveConnection_1", conn_tHiveConnection_1);
	if (null != conn_tHiveConnection_1) {
		
	}

	globalMap.put("current_client_path_separator", System.getProperty("path.separator"));
	System.setProperty("path.separator", ":");

	java.sql.Statement init_tHiveConnection_1 = conn_tHiveConnection_1.createStatement();
			init_tHiveConnection_1.execute("SET dfs.client.use.datanode.hostname=true");
			init_tHiveConnection_1.execute("SET "+"hive.exec.dynamic.partition"+"="+"true");
			init_tHiveConnection_1.execute("SET "+"hive.exec.dynamic.partition.mode"+"="+"nonstrict");
			init_tHiveConnection_1.execute("SET "+"hive.enforce.bucketing"+"="+"true");
			init_tHiveConnection_1.execute("SET "+"hive.conf.validation"+"="+"false");

	

	

	init_tHiveConnection_1.close();

	
	globalMap.put("conn_tHiveConnection_1",conn_tHiveConnection_1);

	globalMap.put("db_tHiveConnection_1","default");

	String currentClientPathSeparator_tHiveConnection_1 = (String)globalMap.get("current_client_path_separator");
	if(currentClientPathSeparator_tHiveConnection_1!=null) {
		System.setProperty("path.separator", currentClientPathSeparator_tHiveConnection_1);
		globalMap.put("current_client_path_separator", null);
	}

	String currentClientUsername_tHiveConnection_1 = (String)globalMap.get("current_client_user_name");
	if(currentClientUsername_tHiveConnection_1!=null) {
		System.setProperty("user.name", currentClientUsername_tHiveConnection_1);
		globalMap.put("current_client_user_name", null);
	}

	String originalHadoopUsername_tHiveConnection_1 = (String)globalMap.get("HADOOP_USER_NAME_tHiveConnection_1");
	if(originalHadoopUsername_tHiveConnection_1!=null) {
		System.setProperty("HADOOP_USER_NAME", originalHadoopUsername_tHiveConnection_1);
		globalMap.put("HADOOP_USER_NAME_tHiveConnection_1", null);
	} else {
		System.clearProperty("HADOOP_USER_NAME");
	}
 



/**
 * [tHiveConnection_1 begin ] stop
 */
	
	/**
	 * [tHiveConnection_1 main ] start
	 */

	

	
	
	currentComponent="tHiveConnection_1";

	

 


	tos_count_tHiveConnection_1++;

/**
 * [tHiveConnection_1 main ] stop
 */
	
	/**
	 * [tHiveConnection_1 process_data_begin ] start
	 */

	

	
	
	currentComponent="tHiveConnection_1";

	

 



/**
 * [tHiveConnection_1 process_data_begin ] stop
 */
	
	/**
	 * [tHiveConnection_1 process_data_end ] start
	 */

	

	
	
	currentComponent="tHiveConnection_1";

	

 



/**
 * [tHiveConnection_1 process_data_end ] stop
 */
	
	/**
	 * [tHiveConnection_1 end ] start
	 */

	

	
	
	currentComponent="tHiveConnection_1";

	

 

ok_Hash.put("tHiveConnection_1", true);
end_Hash.put("tHiveConnection_1", System.currentTimeMillis());




/**
 * [tHiveConnection_1 end ] stop
 */
				}//end the resume

				
				    			if(resumeEntryMethodName == null || globalResumeTicket){
				    				resumeUtil.addLog("CHECKPOINT", "CONNECTION:SUBJOB_OK:tHiveConnection_1:OnSubjobOk1", "", Thread.currentThread().getId() + "", "", "", "", "", "");
								}	    				    			
					    	
								if(execStat){    	
									runStat.updateStatOnConnection("OnSubjobOk2", 0, "ok");
								} 
							
							tHiveRow_1Process(globalMap); 
						
				    			if(resumeEntryMethodName == null || globalResumeTicket){
				    				resumeUtil.addLog("CHECKPOINT", "CONNECTION:SUBJOB_OK:tHiveConnection_1:OnSubjobOk2", "", Thread.currentThread().getId() + "", "", "", "", "", "");
								}	    				    			
					    	
								if(execStat){    	
									runStat.updateStatOnConnection("OnSubjobOk6", 0, "ok");
								} 
							
							tHiveRow_2Process(globalMap); 
						



	
			}catch(java.lang.Exception e){	
				
				TalendException te = new TalendException(e, currentComponent, globalMap);
				
				throw te;
			}catch(java.lang.Error error){	
				
					runStat.stopThreadStat();
				
				throw error;
			}finally{
				
				try{
					
	
	/**
	 * [tHiveConnection_1 finally ] start
	 */

	

	
	
	currentComponent="tHiveConnection_1";

	

 



/**
 * [tHiveConnection_1 finally ] stop
 */
				}catch(java.lang.Exception e){	
					//ignore
				}catch(java.lang.Error error){
					//ignore
				}
				resourceMap = null;
			}
		

		globalMap.put("tHiveConnection_1_SUBPROCESS_STATE", 1);
	}
	

public void tHiveRow_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
	globalMap.put("tHiveRow_1_SUBPROCESS_STATE", 0);

 final boolean execStat = this.execStat;
	
		String iterateId = "";
	
	
	String currentComponent = "";
	java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

	try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { //start the resume
				globalResumeTicket = true;



		


	
	/**
	 * [tHiveRow_1 begin ] start
	 */

	

	
		
		ok_Hash.put("tHiveRow_1", false);
		start_Hash.put("tHiveRow_1", System.currentTimeMillis());
		
	
	currentComponent="tHiveRow_1";

	
		int tos_count_tHiveRow_1 = 0;
		


		


java.sql.Connection conn_tHiveRow_1 = null;
	globalMap.put("current_client_path_separator", System.getProperty("path.separator"));
	System.setProperty("path.separator", ":");
		conn_tHiveRow_1 = (java.sql.Connection)globalMap.get("conn_tHiveConnection_1");

		String dbname_tHiveRow_1 = (String)globalMap.get("db_tHiveConnection_1");
    	if(dbname_tHiveRow_1!=null && !"".equals(dbname_tHiveRow_1.trim()) && !"default".equals(dbname_tHiveRow_1.trim())) {
        	java.sql.Statement goToDatabase_tHiveRow_1 = conn_tHiveRow_1.createStatement();
        	goToDatabase_tHiveRow_1.execute("use " + dbname_tHiveRow_1);
        	goToDatabase_tHiveRow_1.close();
    	}

    	String dbUser_tHiveRow_1 = (String)globalMap.get("dbUser_tHiveConnection_1");

    	globalMap.put("HADOOP_USER_NAME_tHiveRow_1", System.getProperty("HADOOP_USER_NAME"));
		if(dbUser_tHiveRow_1!=null && !"".equals(dbUser_tHiveRow_1.trim())) {
			System.setProperty("HADOOP_USER_NAME",dbUser_tHiveRow_1);
			//make relative file path work for hive
			globalMap.put("current_client_user_name", System.getProperty("user.name"));
			System.setProperty("user.name",dbUser_tHiveRow_1);
		}
		
		java.sql.Statement stmt_tHiveRow_1 = conn_tHiveRow_1.createStatement();
		
	String query_tHiveRow_1 = "";
	boolean whetherReject_tHiveRow_1 = false;
 



/**
 * [tHiveRow_1 begin ] stop
 */
	
	/**
	 * [tHiveRow_1 main ] start
	 */

	

	
	
	currentComponent="tHiveRow_1";

	

	query_tHiveRow_1 = "DROP TABLE IF EXISTS " + context.HoscoStageHo;
	whetherReject_tHiveRow_1 = false;

	
	globalMap.put("tHiveRow_1_QUERY",query_tHiveRow_1);
	
	try {
		

java.text.DateFormat dateStrFormat_tHiveRow_1 = new java.text.SimpleDateFormat("yyyyMMddHHmmss");
final String queryIdentifier_tHiveRow_1 = projectName + "_" + jobName + "_" + jobVersion.replace(".", "_") + "_tHiveRow_1_" + dateStrFormat_tHiveRow_1.format(new Date(startTime));
// For MapReduce Mode
stmt_tHiveRow_1.execute("set mapred.job.name=" + queryIdentifier_tHiveRow_1);
		
		  	stmt_tHiveRow_1.execute(query_tHiveRow_1);
	    	
		
	    } catch (java.lang.Exception e) {
	        whetherReject_tHiveRow_1 = true;
	        
	            throw(e);
	            
	    }
		
	    if(!whetherReject_tHiveRow_1) {
	        
	    }
	    

 


	tos_count_tHiveRow_1++;

/**
 * [tHiveRow_1 main ] stop
 */
	
	/**
	 * [tHiveRow_1 process_data_begin ] start
	 */

	

	
	
	currentComponent="tHiveRow_1";

	

 



/**
 * [tHiveRow_1 process_data_begin ] stop
 */
	
	/**
	 * [tHiveRow_1 process_data_end ] start
	 */

	

	
	
	currentComponent="tHiveRow_1";

	

 



/**
 * [tHiveRow_1 process_data_end ] stop
 */
	
	/**
	 * [tHiveRow_1 end ] start
	 */

	

	
	
	currentComponent="tHiveRow_1";

	

		stmt_tHiveRow_1.close();	
		
		

		String currentClientPathSeparator_tHiveRow_1 = (String)globalMap.get("current_client_path_separator");
		if(currentClientPathSeparator_tHiveRow_1!=null) {
			System.setProperty("path.separator", currentClientPathSeparator_tHiveRow_1);
			globalMap.put("current_client_path_separator", null);
		}
		
		String currentClientUsername_tHiveRow_1 = (String)globalMap.get("current_client_user_name");
		if(currentClientUsername_tHiveRow_1!=null) {
			System.setProperty("user.name", currentClientUsername_tHiveRow_1);
			globalMap.put("current_client_user_name", null);
		}
		
		String originalHadoopUsername_tHiveRow_1 = (String)globalMap.get("HADOOP_USER_NAME_tHiveRow_1");
		if(originalHadoopUsername_tHiveRow_1!=null) {
			System.setProperty("HADOOP_USER_NAME", originalHadoopUsername_tHiveRow_1);
			globalMap.put("HADOOP_USER_NAME_tHiveRow_1", null);
		} else {
			System.clearProperty("HADOOP_USER_NAME");
		}
 

ok_Hash.put("tHiveRow_1", true);
end_Hash.put("tHiveRow_1", System.currentTimeMillis());




/**
 * [tHiveRow_1 end ] stop
 */
				}//end the resume

				
				    			if(resumeEntryMethodName == null || globalResumeTicket){
				    				resumeUtil.addLog("CHECKPOINT", "CONNECTION:SUBJOB_OK:tHiveRow_1:OnSubjobOk", "", Thread.currentThread().getId() + "", "", "", "", "", "");
								}	    				    			
					    	
								if(execStat){    	
									runStat.updateStatOnConnection("OnSubjobOk1", 0, "ok");
								} 
							
							tHiveCreateTable_1Process(globalMap); 
						



	
			}catch(java.lang.Exception e){	
				
				TalendException te = new TalendException(e, currentComponent, globalMap);
				
				throw te;
			}catch(java.lang.Error error){	
				
					runStat.stopThreadStat();
				
				throw error;
			}finally{
				
				try{
					
	
	/**
	 * [tHiveRow_1 finally ] start
	 */

	

	
	
	currentComponent="tHiveRow_1";

	

 



/**
 * [tHiveRow_1 finally ] stop
 */
				}catch(java.lang.Exception e){	
					//ignore
				}catch(java.lang.Error error){
					//ignore
				}
				resourceMap = null;
			}
		

		globalMap.put("tHiveRow_1_SUBPROCESS_STATE", 1);
	}
	

public void tHiveCreateTable_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
	globalMap.put("tHiveCreateTable_1_SUBPROCESS_STATE", 0);

 final boolean execStat = this.execStat;
	
		String iterateId = "";
	
	
	String currentComponent = "";
	java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

	try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { //start the resume
				globalResumeTicket = true;



		


	
	/**
	 * [tHiveCreateTable_1 begin ] start
	 */

	

	
		
		ok_Hash.put("tHiveCreateTable_1", false);
		start_Hash.put("tHiveCreateTable_1", System.currentTimeMillis());
		
	
	currentComponent="tHiveCreateTable_1";

	
		int tos_count_tHiveCreateTable_1 = 0;
		

 



/**
 * [tHiveCreateTable_1 begin ] stop
 */
	
	/**
	 * [tHiveCreateTable_1 main ] start
	 */

	

	
	
	currentComponent="tHiveCreateTable_1";

	


    	


java.sql.Connection conn_tHiveCreateTable_1 = null;
	globalMap.put("current_client_path_separator", System.getProperty("path.separator"));
	System.setProperty("path.separator", ":");
		conn_tHiveCreateTable_1 = (java.sql.Connection)globalMap.get("conn_tHiveConnection_1");

		String dbname_tHiveCreateTable_1 = (String)globalMap.get("db_tHiveConnection_1");
    	if(dbname_tHiveCreateTable_1!=null && !"".equals(dbname_tHiveCreateTable_1.trim()) && !"default".equals(dbname_tHiveCreateTable_1.trim())) {
        	java.sql.Statement goToDatabase_tHiveCreateTable_1 = conn_tHiveCreateTable_1.createStatement();
        	goToDatabase_tHiveCreateTable_1.execute("use " + dbname_tHiveCreateTable_1);
        	goToDatabase_tHiveCreateTable_1.close();
    	}

    	String dbUser_tHiveCreateTable_1 = (String)globalMap.get("dbUser_tHiveConnection_1");

    	globalMap.put("HADOOP_USER_NAME_tHiveCreateTable_1", System.getProperty("HADOOP_USER_NAME"));
		if(dbUser_tHiveCreateTable_1!=null && !"".equals(dbUser_tHiveCreateTable_1.trim())) {
			System.setProperty("HADOOP_USER_NAME",dbUser_tHiveCreateTable_1);
			//make relative file path work for hive
			globalMap.put("current_client_user_name", System.getProperty("user.name"));
			System.setProperty("user.name",dbUser_tHiveCreateTable_1);
		}
		
    java.sql.Statement stmt_tHiveCreateTable_1 = conn_tHiveCreateTable_1.createStatement();
    String query_tHiveCreateTable_1 = "";
    String tableName_tHiveCreateTable_1 = context.HoscoStageHo;
            String fieldChar_tHiveCreateTable_1 = ";";
            String lineChar_tHiveCreateTable_1 = "\n";
String querySQL_tHiveCreateTable_1 = "CREATE  TABLE  " + tableName_tHiveCreateTable_1 + "(Id_patient INT,Num_Hospitalisation STRING) ROW FORMAT DELIMITED  FIELDS TERMINATED BY '" + fieldChar_tHiveCreateTable_1 + "' LINES TERMINATED BY '" + lineChar_tHiveCreateTable_1 + "' STORED AS TEXTFILE";
		try {
			

java.text.DateFormat dateStrFormat_tHiveCreateTable_1 = new java.text.SimpleDateFormat("yyyyMMddHHmmss");
final String queryIdentifier_tHiveCreateTable_1 = projectName + "_" + jobName + "_" + jobVersion.replace(".", "_") + "_tHiveCreateTable_1_" + dateStrFormat_tHiveCreateTable_1.format(new Date(startTime));
// For MapReduce Mode
stmt_tHiveCreateTable_1.execute("set mapred.job.name=" + queryIdentifier_tHiveCreateTable_1);
		    stmt_tHiveCreateTable_1.execute(querySQL_tHiveCreateTable_1);
		} catch(java.sql.SQLException e_tHiveCreateTable_1) {
        		System.err.println(e_tHiveCreateTable_1.getMessage());
        }
		stmt_tHiveCreateTable_1.close();
		
		globalMap.put("tHiveCreateTable_1_QUERY", querySQL_tHiveCreateTable_1);
		
		String currentClientPathSeparator_tHiveCreateTable_1 = (String)globalMap.get("current_client_path_separator");
		if(currentClientPathSeparator_tHiveCreateTable_1!=null) {
		    System.setProperty("path.separator", currentClientPathSeparator_tHiveCreateTable_1);
		    globalMap.put("current_client_path_separator", null);
		}
		
		String currentClientUsername_tHiveCreateTable_1 = (String)globalMap.get("current_client_user_name");
		if(currentClientUsername_tHiveCreateTable_1!=null) {
		    System.setProperty("user.name", currentClientUsername_tHiveCreateTable_1);
		    globalMap.put("current_client_user_name", null);
		}
		
		String originalHadoopUsername_tHiveCreateTable_1 = (String)globalMap.get("HADOOP_USER_NAME_tHiveCreateTable_1");
		if(originalHadoopUsername_tHiveCreateTable_1!=null) {
		    System.setProperty("HADOOP_USER_NAME", originalHadoopUsername_tHiveCreateTable_1);
		    globalMap.put("HADOOP_USER_NAME_tHiveCreateTable_1", null);
		} else {
		    System.clearProperty("HADOOP_USER_NAME");
		}
 


	tos_count_tHiveCreateTable_1++;

/**
 * [tHiveCreateTable_1 main ] stop
 */
	
	/**
	 * [tHiveCreateTable_1 process_data_begin ] start
	 */

	

	
	
	currentComponent="tHiveCreateTable_1";

	

 



/**
 * [tHiveCreateTable_1 process_data_begin ] stop
 */
	
	/**
	 * [tHiveCreateTable_1 process_data_end ] start
	 */

	

	
	
	currentComponent="tHiveCreateTable_1";

	

 



/**
 * [tHiveCreateTable_1 process_data_end ] stop
 */
	
	/**
	 * [tHiveCreateTable_1 end ] start
	 */

	

	
	
	currentComponent="tHiveCreateTable_1";

	

 

ok_Hash.put("tHiveCreateTable_1", true);
end_Hash.put("tHiveCreateTable_1", System.currentTimeMillis());




/**
 * [tHiveCreateTable_1 end ] stop
 */
				}//end the resume

				
				    			if(resumeEntryMethodName == null || globalResumeTicket){
				    				resumeUtil.addLog("CHECKPOINT", "CONNECTION:SUBJOB_OK:tHiveCreateTable_1:OnSubjobOk", "", Thread.currentThread().getId() + "", "", "", "", "", "");
								}	    				    			
					    	
								if(execStat){    	
									runStat.updateStatOnConnection("OnSubjobOk3", 0, "ok");
								} 
							
							tHiveLoad_1Process(globalMap); 
						



	
			}catch(java.lang.Exception e){	
				
				TalendException te = new TalendException(e, currentComponent, globalMap);
				
				throw te;
			}catch(java.lang.Error error){	
				
					runStat.stopThreadStat();
				
				throw error;
			}finally{
				
				try{
					
	
	/**
	 * [tHiveCreateTable_1 finally ] start
	 */

	

	
	
	currentComponent="tHiveCreateTable_1";

	

 



/**
 * [tHiveCreateTable_1 finally ] stop
 */
				}catch(java.lang.Exception e){	
					//ignore
				}catch(java.lang.Error error){
					//ignore
				}
				resourceMap = null;
			}
		

		globalMap.put("tHiveCreateTable_1_SUBPROCESS_STATE", 1);
	}
	

public void tHiveLoad_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
	globalMap.put("tHiveLoad_1_SUBPROCESS_STATE", 0);

 final boolean execStat = this.execStat;
	
		String iterateId = "";
	
	
	String currentComponent = "";
	java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

	try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { //start the resume
				globalResumeTicket = true;





	
	/**
	 * [tHiveLoad_1 begin ] start
	 */

	

	
		
		ok_Hash.put("tHiveLoad_1", false);
		start_Hash.put("tHiveLoad_1", System.currentTimeMillis());
		
	
	currentComponent="tHiveLoad_1";

	
		int tos_count_tHiveLoad_1 = 0;
		

 



/**
 * [tHiveLoad_1 begin ] stop
 */
	
	/**
	 * [tHiveLoad_1 main ] start
	 */

	

	
	
	currentComponent="tHiveLoad_1";

	




java.sql.Connection conn_tHiveLoad_1 = null;
	globalMap.put("current_client_path_separator", System.getProperty("path.separator"));
	System.setProperty("path.separator", ":");
		conn_tHiveLoad_1 = (java.sql.Connection)globalMap.get("conn_tHiveConnection_1");

		String dbname_tHiveLoad_1 = (String)globalMap.get("db_tHiveConnection_1");
    	if(dbname_tHiveLoad_1!=null && !"".equals(dbname_tHiveLoad_1.trim()) && !"default".equals(dbname_tHiveLoad_1.trim())) {
        	java.sql.Statement goToDatabase_tHiveLoad_1 = conn_tHiveLoad_1.createStatement();
        	goToDatabase_tHiveLoad_1.execute("use " + dbname_tHiveLoad_1);
        	goToDatabase_tHiveLoad_1.close();
    	}

    	String dbUser_tHiveLoad_1 = (String)globalMap.get("dbUser_tHiveConnection_1");

    	globalMap.put("HADOOP_USER_NAME_tHiveLoad_1", System.getProperty("HADOOP_USER_NAME"));
		if(dbUser_tHiveLoad_1!=null && !"".equals(dbUser_tHiveLoad_1.trim())) {
			System.setProperty("HADOOP_USER_NAME",dbUser_tHiveLoad_1);
			//make relative file path work for hive
			globalMap.put("current_client_user_name", System.getProperty("user.name"));
			System.setProperty("user.name",dbUser_tHiveLoad_1);
		}
		
			String path_tHiveLoad_1 = "/user/cloudera/" + context.HadoopHDFS_HoscoHo;
		String tablename_tHiveLoad_1 = context.HoscoStageHo;

	String querySQL_tHiveLoad_1 = "LOAD DATA INPATH '" + path_tHiveLoad_1 + "' OVERWRITE  INTO TABLE " + tablename_tHiveLoad_1 + "";
	
        java.sql.Statement stmt_tHiveLoad_1 = conn_tHiveLoad_1.createStatement();
        try {
			

java.text.DateFormat dateStrFormat_tHiveLoad_1 = new java.text.SimpleDateFormat("yyyyMMddHHmmss");
final String queryIdentifier_tHiveLoad_1 = projectName + "_" + jobName + "_" + jobVersion.replace(".", "_") + "_tHiveLoad_1_" + dateStrFormat_tHiveLoad_1.format(new Date(startTime));
// For MapReduce Mode
stmt_tHiveLoad_1.execute("set mapred.job.name=" + queryIdentifier_tHiveLoad_1);
            stmt_tHiveLoad_1.execute(querySQL_tHiveLoad_1);
        } catch(java.sql.SQLException e_tHiveLoad_1) {
                System.err.println(e_tHiveLoad_1.getMessage());
        }
        stmt_tHiveLoad_1.close();
        globalMap.put("tHiveLoad_1_QUERY", querySQL_tHiveLoad_1);

        String currentClientPathSeparator_tHiveLoad_1 = (String)globalMap.get("current_client_path_separator");
        if(currentClientPathSeparator_tHiveLoad_1!=null) {
            System.setProperty("path.separator", currentClientPathSeparator_tHiveLoad_1);
            globalMap.put("current_client_path_separator", null);
        }

        String currentClientUsername_tHiveLoad_1 = (String)globalMap.get("current_client_user_name");
        if(currentClientUsername_tHiveLoad_1!=null) {
            System.setProperty("user.name", currentClientUsername_tHiveLoad_1);
            globalMap.put("current_client_user_name", null);
        }

        String originalHadoopUsername_tHiveLoad_1 = (String)globalMap.get("HADOOP_USER_NAME_tHiveLoad_1");
        if(originalHadoopUsername_tHiveLoad_1!=null) {
            System.setProperty("HADOOP_USER_NAME", originalHadoopUsername_tHiveLoad_1);
            globalMap.put("HADOOP_USER_NAME_tHiveLoad_1", null);
        } else {
            System.clearProperty("HADOOP_USER_NAME");
        }
 


	tos_count_tHiveLoad_1++;

/**
 * [tHiveLoad_1 main ] stop
 */
	
	/**
	 * [tHiveLoad_1 process_data_begin ] start
	 */

	

	
	
	currentComponent="tHiveLoad_1";

	

 



/**
 * [tHiveLoad_1 process_data_begin ] stop
 */
	
	/**
	 * [tHiveLoad_1 process_data_end ] start
	 */

	

	
	
	currentComponent="tHiveLoad_1";

	

 



/**
 * [tHiveLoad_1 process_data_end ] stop
 */
	
	/**
	 * [tHiveLoad_1 end ] start
	 */

	

	
	
	currentComponent="tHiveLoad_1";

	

 

ok_Hash.put("tHiveLoad_1", true);
end_Hash.put("tHiveLoad_1", System.currentTimeMillis());




/**
 * [tHiveLoad_1 end ] stop
 */
				}//end the resume

				



	
			}catch(java.lang.Exception e){	
				
				TalendException te = new TalendException(e, currentComponent, globalMap);
				
				throw te;
			}catch(java.lang.Error error){	
				
					runStat.stopThreadStat();
				
				throw error;
			}finally{
				
				try{
					
	
	/**
	 * [tHiveLoad_1 finally ] start
	 */

	

	
	
	currentComponent="tHiveLoad_1";

	

 



/**
 * [tHiveLoad_1 finally ] stop
 */
				}catch(java.lang.Exception e){	
					//ignore
				}catch(java.lang.Error error){
					//ignore
				}
				resourceMap = null;
			}
		

		globalMap.put("tHiveLoad_1_SUBPROCESS_STATE", 1);
	}
	

public void tHiveRow_2Process(final java.util.Map<String, Object> globalMap) throws TalendException {
	globalMap.put("tHiveRow_2_SUBPROCESS_STATE", 0);

 final boolean execStat = this.execStat;
	
		String iterateId = "";
	
	
	String currentComponent = "";
	java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

	try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { //start the resume
				globalResumeTicket = true;



		


	
	/**
	 * [tHiveRow_2 begin ] start
	 */

	

	
		
		ok_Hash.put("tHiveRow_2", false);
		start_Hash.put("tHiveRow_2", System.currentTimeMillis());
		
	
	currentComponent="tHiveRow_2";

	
		int tos_count_tHiveRow_2 = 0;
		


		


java.sql.Connection conn_tHiveRow_2 = null;
	globalMap.put("current_client_path_separator", System.getProperty("path.separator"));
	System.setProperty("path.separator", ":");
		conn_tHiveRow_2 = (java.sql.Connection)globalMap.get("conn_tHiveConnection_1");

		String dbname_tHiveRow_2 = (String)globalMap.get("db_tHiveConnection_1");
    	if(dbname_tHiveRow_2!=null && !"".equals(dbname_tHiveRow_2.trim()) && !"default".equals(dbname_tHiveRow_2.trim())) {
        	java.sql.Statement goToDatabase_tHiveRow_2 = conn_tHiveRow_2.createStatement();
        	goToDatabase_tHiveRow_2.execute("use " + dbname_tHiveRow_2);
        	goToDatabase_tHiveRow_2.close();
    	}

    	String dbUser_tHiveRow_2 = (String)globalMap.get("dbUser_tHiveConnection_1");

    	globalMap.put("HADOOP_USER_NAME_tHiveRow_2", System.getProperty("HADOOP_USER_NAME"));
		if(dbUser_tHiveRow_2!=null && !"".equals(dbUser_tHiveRow_2.trim())) {
			System.setProperty("HADOOP_USER_NAME",dbUser_tHiveRow_2);
			//make relative file path work for hive
			globalMap.put("current_client_user_name", System.getProperty("user.name"));
			System.setProperty("user.name",dbUser_tHiveRow_2);
		}
		
		java.sql.Statement stmt_tHiveRow_2 = conn_tHiveRow_2.createStatement();
		
	String query_tHiveRow_2 = "";
	boolean whetherReject_tHiveRow_2 = false;
 



/**
 * [tHiveRow_2 begin ] stop
 */
	
	/**
	 * [tHiveRow_2 main ] start
	 */

	

	
	
	currentComponent="tHiveRow_2";

	

	query_tHiveRow_2 = "DROP TABLE IF EXISTS " + context.HoscoStageCo;
	whetherReject_tHiveRow_2 = false;

	
	globalMap.put("tHiveRow_2_QUERY",query_tHiveRow_2);
	
	try {
		

java.text.DateFormat dateStrFormat_tHiveRow_2 = new java.text.SimpleDateFormat("yyyyMMddHHmmss");
final String queryIdentifier_tHiveRow_2 = projectName + "_" + jobName + "_" + jobVersion.replace(".", "_") + "_tHiveRow_2_" + dateStrFormat_tHiveRow_2.format(new Date(startTime));
// For MapReduce Mode
stmt_tHiveRow_2.execute("set mapred.job.name=" + queryIdentifier_tHiveRow_2);
		
		  	stmt_tHiveRow_2.execute(query_tHiveRow_2);
	    	
		
	    } catch (java.lang.Exception e) {
	        whetherReject_tHiveRow_2 = true;
	        
	            throw(e);
	            
	    }
		
	    if(!whetherReject_tHiveRow_2) {
	        
	    }
	    

 


	tos_count_tHiveRow_2++;

/**
 * [tHiveRow_2 main ] stop
 */
	
	/**
	 * [tHiveRow_2 process_data_begin ] start
	 */

	

	
	
	currentComponent="tHiveRow_2";

	

 



/**
 * [tHiveRow_2 process_data_begin ] stop
 */
	
	/**
	 * [tHiveRow_2 process_data_end ] start
	 */

	

	
	
	currentComponent="tHiveRow_2";

	

 



/**
 * [tHiveRow_2 process_data_end ] stop
 */
	
	/**
	 * [tHiveRow_2 end ] start
	 */

	

	
	
	currentComponent="tHiveRow_2";

	

		stmt_tHiveRow_2.close();	
		
		

		String currentClientPathSeparator_tHiveRow_2 = (String)globalMap.get("current_client_path_separator");
		if(currentClientPathSeparator_tHiveRow_2!=null) {
			System.setProperty("path.separator", currentClientPathSeparator_tHiveRow_2);
			globalMap.put("current_client_path_separator", null);
		}
		
		String currentClientUsername_tHiveRow_2 = (String)globalMap.get("current_client_user_name");
		if(currentClientUsername_tHiveRow_2!=null) {
			System.setProperty("user.name", currentClientUsername_tHiveRow_2);
			globalMap.put("current_client_user_name", null);
		}
		
		String originalHadoopUsername_tHiveRow_2 = (String)globalMap.get("HADOOP_USER_NAME_tHiveRow_2");
		if(originalHadoopUsername_tHiveRow_2!=null) {
			System.setProperty("HADOOP_USER_NAME", originalHadoopUsername_tHiveRow_2);
			globalMap.put("HADOOP_USER_NAME_tHiveRow_2", null);
		} else {
			System.clearProperty("HADOOP_USER_NAME");
		}
 

ok_Hash.put("tHiveRow_2", true);
end_Hash.put("tHiveRow_2", System.currentTimeMillis());




/**
 * [tHiveRow_2 end ] stop
 */
				}//end the resume

				
				    			if(resumeEntryMethodName == null || globalResumeTicket){
				    				resumeUtil.addLog("CHECKPOINT", "CONNECTION:SUBJOB_OK:tHiveRow_2:OnSubjobOk", "", Thread.currentThread().getId() + "", "", "", "", "", "");
								}	    				    			
					    	
								if(execStat){    	
									runStat.updateStatOnConnection("OnSubjobOk4", 0, "ok");
								} 
							
							tHiveCreateTable_2Process(globalMap); 
						



	
			}catch(java.lang.Exception e){	
				
				TalendException te = new TalendException(e, currentComponent, globalMap);
				
				throw te;
			}catch(java.lang.Error error){	
				
					runStat.stopThreadStat();
				
				throw error;
			}finally{
				
				try{
					
	
	/**
	 * [tHiveRow_2 finally ] start
	 */

	

	
	
	currentComponent="tHiveRow_2";

	

 



/**
 * [tHiveRow_2 finally ] stop
 */
				}catch(java.lang.Exception e){	
					//ignore
				}catch(java.lang.Error error){
					//ignore
				}
				resourceMap = null;
			}
		

		globalMap.put("tHiveRow_2_SUBPROCESS_STATE", 1);
	}
	

public void tHiveCreateTable_2Process(final java.util.Map<String, Object> globalMap) throws TalendException {
	globalMap.put("tHiveCreateTable_2_SUBPROCESS_STATE", 0);

 final boolean execStat = this.execStat;
	
		String iterateId = "";
	
	
	String currentComponent = "";
	java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

	try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { //start the resume
				globalResumeTicket = true;



		


	
	/**
	 * [tHiveCreateTable_2 begin ] start
	 */

	

	
		
		ok_Hash.put("tHiveCreateTable_2", false);
		start_Hash.put("tHiveCreateTable_2", System.currentTimeMillis());
		
	
	currentComponent="tHiveCreateTable_2";

	
		int tos_count_tHiveCreateTable_2 = 0;
		

 



/**
 * [tHiveCreateTable_2 begin ] stop
 */
	
	/**
	 * [tHiveCreateTable_2 main ] start
	 */

	

	
	
	currentComponent="tHiveCreateTable_2";

	


    	


java.sql.Connection conn_tHiveCreateTable_2 = null;
	globalMap.put("current_client_path_separator", System.getProperty("path.separator"));
	System.setProperty("path.separator", ":");
		conn_tHiveCreateTable_2 = (java.sql.Connection)globalMap.get("conn_tHiveConnection_1");

		String dbname_tHiveCreateTable_2 = (String)globalMap.get("db_tHiveConnection_1");
    	if(dbname_tHiveCreateTable_2!=null && !"".equals(dbname_tHiveCreateTable_2.trim()) && !"default".equals(dbname_tHiveCreateTable_2.trim())) {
        	java.sql.Statement goToDatabase_tHiveCreateTable_2 = conn_tHiveCreateTable_2.createStatement();
        	goToDatabase_tHiveCreateTable_2.execute("use " + dbname_tHiveCreateTable_2);
        	goToDatabase_tHiveCreateTable_2.close();
    	}

    	String dbUser_tHiveCreateTable_2 = (String)globalMap.get("dbUser_tHiveConnection_1");

    	globalMap.put("HADOOP_USER_NAME_tHiveCreateTable_2", System.getProperty("HADOOP_USER_NAME"));
		if(dbUser_tHiveCreateTable_2!=null && !"".equals(dbUser_tHiveCreateTable_2.trim())) {
			System.setProperty("HADOOP_USER_NAME",dbUser_tHiveCreateTable_2);
			//make relative file path work for hive
			globalMap.put("current_client_user_name", System.getProperty("user.name"));
			System.setProperty("user.name",dbUser_tHiveCreateTable_2);
		}
		
    java.sql.Statement stmt_tHiveCreateTable_2 = conn_tHiveCreateTable_2.createStatement();
    String query_tHiveCreateTable_2 = "";
    String tableName_tHiveCreateTable_2 = context.HoscoStageCo;
            String fieldChar_tHiveCreateTable_2 = ";";
            String lineChar_tHiveCreateTable_2 = "\n";
String querySQL_tHiveCreateTable_2 = "CREATE  TABLE  " + tableName_tHiveCreateTable_2 + "(Id_patient INT,Num_consultation INT) ROW FORMAT DELIMITED  FIELDS TERMINATED BY '" + fieldChar_tHiveCreateTable_2 + "' LINES TERMINATED BY '" + lineChar_tHiveCreateTable_2 + "' STORED AS TEXTFILE";
		try {
			

java.text.DateFormat dateStrFormat_tHiveCreateTable_2 = new java.text.SimpleDateFormat("yyyyMMddHHmmss");
final String queryIdentifier_tHiveCreateTable_2 = projectName + "_" + jobName + "_" + jobVersion.replace(".", "_") + "_tHiveCreateTable_2_" + dateStrFormat_tHiveCreateTable_2.format(new Date(startTime));
// For MapReduce Mode
stmt_tHiveCreateTable_2.execute("set mapred.job.name=" + queryIdentifier_tHiveCreateTable_2);
		    stmt_tHiveCreateTable_2.execute(querySQL_tHiveCreateTable_2);
		} catch(java.sql.SQLException e_tHiveCreateTable_2) {
        		System.err.println(e_tHiveCreateTable_2.getMessage());
        }
		stmt_tHiveCreateTable_2.close();
		
		globalMap.put("tHiveCreateTable_2_QUERY", querySQL_tHiveCreateTable_2);
		
		String currentClientPathSeparator_tHiveCreateTable_2 = (String)globalMap.get("current_client_path_separator");
		if(currentClientPathSeparator_tHiveCreateTable_2!=null) {
		    System.setProperty("path.separator", currentClientPathSeparator_tHiveCreateTable_2);
		    globalMap.put("current_client_path_separator", null);
		}
		
		String currentClientUsername_tHiveCreateTable_2 = (String)globalMap.get("current_client_user_name");
		if(currentClientUsername_tHiveCreateTable_2!=null) {
		    System.setProperty("user.name", currentClientUsername_tHiveCreateTable_2);
		    globalMap.put("current_client_user_name", null);
		}
		
		String originalHadoopUsername_tHiveCreateTable_2 = (String)globalMap.get("HADOOP_USER_NAME_tHiveCreateTable_2");
		if(originalHadoopUsername_tHiveCreateTable_2!=null) {
		    System.setProperty("HADOOP_USER_NAME", originalHadoopUsername_tHiveCreateTable_2);
		    globalMap.put("HADOOP_USER_NAME_tHiveCreateTable_2", null);
		} else {
		    System.clearProperty("HADOOP_USER_NAME");
		}
 


	tos_count_tHiveCreateTable_2++;

/**
 * [tHiveCreateTable_2 main ] stop
 */
	
	/**
	 * [tHiveCreateTable_2 process_data_begin ] start
	 */

	

	
	
	currentComponent="tHiveCreateTable_2";

	

 



/**
 * [tHiveCreateTable_2 process_data_begin ] stop
 */
	
	/**
	 * [tHiveCreateTable_2 process_data_end ] start
	 */

	

	
	
	currentComponent="tHiveCreateTable_2";

	

 



/**
 * [tHiveCreateTable_2 process_data_end ] stop
 */
	
	/**
	 * [tHiveCreateTable_2 end ] start
	 */

	

	
	
	currentComponent="tHiveCreateTable_2";

	

 

ok_Hash.put("tHiveCreateTable_2", true);
end_Hash.put("tHiveCreateTable_2", System.currentTimeMillis());




/**
 * [tHiveCreateTable_2 end ] stop
 */
				}//end the resume

				
				    			if(resumeEntryMethodName == null || globalResumeTicket){
				    				resumeUtil.addLog("CHECKPOINT", "CONNECTION:SUBJOB_OK:tHiveCreateTable_2:OnSubjobOk", "", Thread.currentThread().getId() + "", "", "", "", "", "");
								}	    				    			
					    	
								if(execStat){    	
									runStat.updateStatOnConnection("OnSubjobOk5", 0, "ok");
								} 
							
							tHiveLoad_2Process(globalMap); 
						



	
			}catch(java.lang.Exception e){	
				
				TalendException te = new TalendException(e, currentComponent, globalMap);
				
				throw te;
			}catch(java.lang.Error error){	
				
					runStat.stopThreadStat();
				
				throw error;
			}finally{
				
				try{
					
	
	/**
	 * [tHiveCreateTable_2 finally ] start
	 */

	

	
	
	currentComponent="tHiveCreateTable_2";

	

 



/**
 * [tHiveCreateTable_2 finally ] stop
 */
				}catch(java.lang.Exception e){	
					//ignore
				}catch(java.lang.Error error){
					//ignore
				}
				resourceMap = null;
			}
		

		globalMap.put("tHiveCreateTable_2_SUBPROCESS_STATE", 1);
	}
	

public void tHiveLoad_2Process(final java.util.Map<String, Object> globalMap) throws TalendException {
	globalMap.put("tHiveLoad_2_SUBPROCESS_STATE", 0);

 final boolean execStat = this.execStat;
	
		String iterateId = "";
	
	
	String currentComponent = "";
	java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

	try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { //start the resume
				globalResumeTicket = true;





	
	/**
	 * [tHiveLoad_2 begin ] start
	 */

	

	
		
		ok_Hash.put("tHiveLoad_2", false);
		start_Hash.put("tHiveLoad_2", System.currentTimeMillis());
		
	
	currentComponent="tHiveLoad_2";

	
		int tos_count_tHiveLoad_2 = 0;
		

 



/**
 * [tHiveLoad_2 begin ] stop
 */
	
	/**
	 * [tHiveLoad_2 main ] start
	 */

	

	
	
	currentComponent="tHiveLoad_2";

	




java.sql.Connection conn_tHiveLoad_2 = null;
	globalMap.put("current_client_path_separator", System.getProperty("path.separator"));
	System.setProperty("path.separator", ":");
		conn_tHiveLoad_2 = (java.sql.Connection)globalMap.get("conn_tHiveConnection_1");

		String dbname_tHiveLoad_2 = (String)globalMap.get("db_tHiveConnection_1");
    	if(dbname_tHiveLoad_2!=null && !"".equals(dbname_tHiveLoad_2.trim()) && !"default".equals(dbname_tHiveLoad_2.trim())) {
        	java.sql.Statement goToDatabase_tHiveLoad_2 = conn_tHiveLoad_2.createStatement();
        	goToDatabase_tHiveLoad_2.execute("use " + dbname_tHiveLoad_2);
        	goToDatabase_tHiveLoad_2.close();
    	}

    	String dbUser_tHiveLoad_2 = (String)globalMap.get("dbUser_tHiveConnection_1");

    	globalMap.put("HADOOP_USER_NAME_tHiveLoad_2", System.getProperty("HADOOP_USER_NAME"));
		if(dbUser_tHiveLoad_2!=null && !"".equals(dbUser_tHiveLoad_2.trim())) {
			System.setProperty("HADOOP_USER_NAME",dbUser_tHiveLoad_2);
			//make relative file path work for hive
			globalMap.put("current_client_user_name", System.getProperty("user.name"));
			System.setProperty("user.name",dbUser_tHiveLoad_2);
		}
		
			String path_tHiveLoad_2 = "/user/cloudera/" + context.HadoopHDFS_HoscoCo;
		String tablename_tHiveLoad_2 = context.HoscoStageCo;

	String querySQL_tHiveLoad_2 = "LOAD DATA INPATH '" + path_tHiveLoad_2 + "' OVERWRITE  INTO TABLE " + tablename_tHiveLoad_2 + "";
	
        java.sql.Statement stmt_tHiveLoad_2 = conn_tHiveLoad_2.createStatement();
        try {
			

java.text.DateFormat dateStrFormat_tHiveLoad_2 = new java.text.SimpleDateFormat("yyyyMMddHHmmss");
final String queryIdentifier_tHiveLoad_2 = projectName + "_" + jobName + "_" + jobVersion.replace(".", "_") + "_tHiveLoad_2_" + dateStrFormat_tHiveLoad_2.format(new Date(startTime));
// For MapReduce Mode
stmt_tHiveLoad_2.execute("set mapred.job.name=" + queryIdentifier_tHiveLoad_2);
            stmt_tHiveLoad_2.execute(querySQL_tHiveLoad_2);
        } catch(java.sql.SQLException e_tHiveLoad_2) {
                System.err.println(e_tHiveLoad_2.getMessage());
        }
        stmt_tHiveLoad_2.close();
        globalMap.put("tHiveLoad_2_QUERY", querySQL_tHiveLoad_2);

        String currentClientPathSeparator_tHiveLoad_2 = (String)globalMap.get("current_client_path_separator");
        if(currentClientPathSeparator_tHiveLoad_2!=null) {
            System.setProperty("path.separator", currentClientPathSeparator_tHiveLoad_2);
            globalMap.put("current_client_path_separator", null);
        }

        String currentClientUsername_tHiveLoad_2 = (String)globalMap.get("current_client_user_name");
        if(currentClientUsername_tHiveLoad_2!=null) {
            System.setProperty("user.name", currentClientUsername_tHiveLoad_2);
            globalMap.put("current_client_user_name", null);
        }

        String originalHadoopUsername_tHiveLoad_2 = (String)globalMap.get("HADOOP_USER_NAME_tHiveLoad_2");
        if(originalHadoopUsername_tHiveLoad_2!=null) {
            System.setProperty("HADOOP_USER_NAME", originalHadoopUsername_tHiveLoad_2);
            globalMap.put("HADOOP_USER_NAME_tHiveLoad_2", null);
        } else {
            System.clearProperty("HADOOP_USER_NAME");
        }
 


	tos_count_tHiveLoad_2++;

/**
 * [tHiveLoad_2 main ] stop
 */
	
	/**
	 * [tHiveLoad_2 process_data_begin ] start
	 */

	

	
	
	currentComponent="tHiveLoad_2";

	

 



/**
 * [tHiveLoad_2 process_data_begin ] stop
 */
	
	/**
	 * [tHiveLoad_2 process_data_end ] start
	 */

	

	
	
	currentComponent="tHiveLoad_2";

	

 



/**
 * [tHiveLoad_2 process_data_end ] stop
 */
	
	/**
	 * [tHiveLoad_2 end ] start
	 */

	

	
	
	currentComponent="tHiveLoad_2";

	

 

ok_Hash.put("tHiveLoad_2", true);
end_Hash.put("tHiveLoad_2", System.currentTimeMillis());




/**
 * [tHiveLoad_2 end ] stop
 */
				}//end the resume

				



	
			}catch(java.lang.Exception e){	
				
				TalendException te = new TalendException(e, currentComponent, globalMap);
				
				throw te;
			}catch(java.lang.Error error){	
				
					runStat.stopThreadStat();
				
				throw error;
			}finally{
				
				try{
					
	
	/**
	 * [tHiveLoad_2 finally ] start
	 */

	

	
	
	currentComponent="tHiveLoad_2";

	

 



/**
 * [tHiveLoad_2 finally ] stop
 */
				}catch(java.lang.Exception e){	
					//ignore
				}catch(java.lang.Error error){
					//ignore
				}
				resourceMap = null;
			}
		

		globalMap.put("tHiveLoad_2_SUBPROCESS_STATE", 1);
	}
	
    public String resuming_logs_dir_path = null;
    public String resuming_checkpoint_path = null;
    public String parent_part_launcher = null;
    private String resumeEntryMethodName = null;
    private boolean globalResumeTicket = false;

    public boolean watch = false;
    // portStats is null, it means don't execute the statistics
    public Integer portStats = null;
    public int portTraces = 4334;
    public String clientHost;
    public String defaultClientHost = "localhost";
    public String contextStr = "Default";
    public boolean isDefaultContext = true;
    public String pid = "0";
    public String rootPid = null;
    public String fatherPid = null;
    public String fatherNode = null;
    public long startTime = 0;
    public boolean isChildJob = false;
    public String log4jLevel = "";
    
    private boolean enableLogStash;

    private boolean execStat = true;

    private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
        protected java.util.Map<String, String> initialValue() {
            java.util.Map<String,String> threadRunResultMap = new java.util.HashMap<String, String>();
            threadRunResultMap.put("errorCode", null);
            threadRunResultMap.put("status", "");
            return threadRunResultMap;
        };
    };


    private PropertiesWithType context_param = new PropertiesWithType();
    public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

    public String status= "";
    

    public static void main(String[] args){
        final Stage_Hosco Stage_HoscoClass = new Stage_Hosco();

        int exitCode = Stage_HoscoClass.runJobInTOS(args);

        System.exit(exitCode);
    }


    public String[][] runJob(String[] args) {

        int exitCode = runJobInTOS(args);
        String[][] bufferValue = new String[][] { { Integer.toString(exitCode) } };

        return bufferValue;
    }

    public boolean hastBufferOutputComponent() {
		boolean hastBufferOutput = false;
    	
        return hastBufferOutput;
    }

    public int runJobInTOS(String[] args) {
	   	// reset status
	   	status = "";
	   	
        String lastStr = "";
        for (String arg : args) {
            if (arg.equalsIgnoreCase("--context_param")) {
                lastStr = arg;
            } else if (lastStr.equals("")) {
                evalParam(arg);
            } else {
                evalParam(lastStr + " " + arg);
                lastStr = "";
            }
        }
        enableLogStash = "true".equalsIgnoreCase(System.getProperty("monitoring"));

    	
    	

        if(clientHost == null) {
            clientHost = defaultClientHost;
        }

        if(pid == null || "0".equals(pid)) {
            pid = TalendString.getAsciiRandomString(6);
        }

        if (rootPid==null) {
            rootPid = pid;
        }
        if (fatherPid==null) {
            fatherPid = pid;
        }else{
            isChildJob = true;
        }

        if (portStats != null) {
            // portStats = -1; //for testing
            if (portStats < 0 || portStats > 65535) {
                // issue:10869, the portStats is invalid, so this client socket can't open
                System.err.println("The statistics socket port " + portStats + " is invalid.");
                execStat = false;
            }
        } else {
            execStat = false;
        }

        try {
            //call job/subjob with an existing context, like: --context=production. if without this parameter, there will use the default context instead.
            java.io.InputStream inContext = Stage_Hosco.class.getClassLoader().getResourceAsStream("bigdata_project/stage_hosco_0_1/contexts/" + contextStr + ".properties");
            if (inContext == null) {
                inContext = Stage_Hosco.class.getClassLoader().getResourceAsStream("config/contexts/" + contextStr + ".properties");
            }
            if (inContext != null) {
                //defaultProps is in order to keep the original context value
                if(context != null && context.isEmpty()) {
	                defaultProps.load(inContext);
	                context = new ContextProperties(defaultProps);
                }
                
                inContext.close();
            } else if (!isDefaultContext) {
                //print info and job continue to run, for case: context_param is not empty.
                System.err.println("Could not find the context " + contextStr);
            }

            if(!context_param.isEmpty()) {
                context.putAll(context_param);
				//set types for params from parentJobs
				for (Object key: context_param.keySet()){
					String context_key = key.toString();
					String context_type = context_param.getContextType(context_key);
					context.setContextType(context_key, context_type);

				}
            }
            class ContextProcessing {
                private void processContext_0() {
                        context.setContextType("HadoopHDFS_HoscoCo", "id_String");
                            context.HadoopHDFS_HoscoCo=(String) context.getProperty("HadoopHDFS_HoscoCo");
                        context.setContextType("HadoopHDFS_HoscoHo", "id_String");
                            context.HadoopHDFS_HoscoHo=(String) context.getProperty("HadoopHDFS_HoscoHo");
                        context.setContextType("HoscoStageCo", "id_String");
                            context.HoscoStageCo=(String) context.getProperty("HoscoStageCo");
                        context.setContextType("HoscoStageHo", "id_String");
                            context.HoscoStageHo=(String) context.getProperty("HoscoStageHo");
                } 
                public void processAllContext() {
                        processContext_0();
                }
            }

            new ContextProcessing().processAllContext();
        } catch (java.io.IOException ie) {
            System.err.println("Could not load context "+contextStr);
            ie.printStackTrace();
        }

        // get context value from parent directly
        if (parentContextMap != null && !parentContextMap.isEmpty()) {if (parentContextMap.containsKey("HadoopHDFS_HoscoCo")) {
                context.HadoopHDFS_HoscoCo = (String) parentContextMap.get("HadoopHDFS_HoscoCo");
            }if (parentContextMap.containsKey("HadoopHDFS_HoscoHo")) {
                context.HadoopHDFS_HoscoHo = (String) parentContextMap.get("HadoopHDFS_HoscoHo");
            }if (parentContextMap.containsKey("HoscoStageCo")) {
                context.HoscoStageCo = (String) parentContextMap.get("HoscoStageCo");
            }if (parentContextMap.containsKey("HoscoStageHo")) {
                context.HoscoStageHo = (String) parentContextMap.get("HoscoStageHo");
            }
        }

        //Resume: init the resumeUtil
        resumeEntryMethodName = ResumeUtil.getResumeEntryMethodName(resuming_checkpoint_path);
        resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
        resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName, jobName, contextStr, jobVersion);

		List<String> parametersToEncrypt = new java.util.ArrayList<String>();
        //Resume: jobStart
        resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "", "","","","",resumeUtil.convertToJsonText(context,parametersToEncrypt));

if(execStat) {
    try {
        runStat.openSocket(!isChildJob);
        runStat.setAllPID(rootPid, fatherPid, pid, jobName);
        runStat.startThreadStat(clientHost, portStats);
        runStat.updateStatOnJob(RunStat.JOBSTART, fatherNode);
    } catch (java.io.IOException ioException) {
        ioException.printStackTrace();
    }
}



	
	    java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
	    globalMap.put("concurrentHashMap", concurrentHashMap);
	

    long startUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
    long endUsedMemory = 0;
    long end = 0;

    startTime = System.currentTimeMillis();




this.globalResumeTicket = true;//to run tPreJob




this.globalResumeTicket = false;//to run others jobs

try {
errorCode = null;tHiveConnection_1Process(globalMap);
if(!"failure".equals(status)) { status = "end"; }
}catch (TalendException e_tHiveConnection_1) {
globalMap.put("tHiveConnection_1_SUBPROCESS_STATE", -1);

e_tHiveConnection_1.printStackTrace();

}

this.globalResumeTicket = true;//to run tPostJob




        end = System.currentTimeMillis();

        if (watch) {
            System.out.println((end-startTime)+" milliseconds");
        }

        endUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
        if (false) {
            System.out.println((endUsedMemory - startUsedMemory) + " bytes memory increase when running : Stage_Hosco");
        }



if (execStat) {
    runStat.updateStatOnJob(RunStat.JOBEND, fatherNode);
    runStat.stopThreadStat();
}
    int returnCode = 0;
    if(errorCode == null) {
         returnCode = status != null && status.equals("failure") ? 1 : 0;
    } else {
         returnCode = errorCode.intValue();
    }
    resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "", "","" + returnCode,"","","");

    return returnCode;

  }

    // only for OSGi env
    public void destroy() {
    closeSqlDbConnections();


    }



    private void closeSqlDbConnections() {
        try {
            Object obj_conn;
            obj_conn = globalMap.remove("conn_tHiveConnection_1");
            if (null != obj_conn) {
                ((java.sql.Connection) obj_conn).close();
            }
        } catch (java.lang.Exception e) {
        }
    }











    private java.util.Map<String, Object> getSharedConnections4REST() {
        java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();
            connections.put("conn_tHiveConnection_1", globalMap.get("conn_tHiveConnection_1"));







        return connections;
    }

    private void evalParam(String arg) {
        if (arg.startsWith("--resuming_logs_dir_path")) {
            resuming_logs_dir_path = arg.substring(25);
        } else if (arg.startsWith("--resuming_checkpoint_path")) {
            resuming_checkpoint_path = arg.substring(27);
        } else if (arg.startsWith("--parent_part_launcher")) {
            parent_part_launcher = arg.substring(23);
        } else if (arg.startsWith("--watch")) {
            watch = true;
        } else if (arg.startsWith("--stat_port=")) {
            String portStatsStr = arg.substring(12);
            if (portStatsStr != null && !portStatsStr.equals("null")) {
                portStats = Integer.parseInt(portStatsStr);
            }
        } else if (arg.startsWith("--trace_port=")) {
            portTraces = Integer.parseInt(arg.substring(13));
        } else if (arg.startsWith("--client_host=")) {
            clientHost = arg.substring(14);
        } else if (arg.startsWith("--context=")) {
            contextStr = arg.substring(10);
            isDefaultContext = false;
        } else if (arg.startsWith("--father_pid=")) {
            fatherPid = arg.substring(13);
        } else if (arg.startsWith("--root_pid=")) {
            rootPid = arg.substring(11);
        } else if (arg.startsWith("--father_node=")) {
            fatherNode = arg.substring(14);
        } else if (arg.startsWith("--pid=")) {
            pid = arg.substring(6);
        } else if (arg.startsWith("--context_type")) {
            String keyValue = arg.substring(15);
			int index = -1;
            if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
                if (fatherPid==null) {
                    context_param.setContextType(keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
                } else { // the subjob won't escape the especial chars
                    context_param.setContextType(keyValue.substring(0, index), keyValue.substring(index + 1) );
                }

            }

		} else if (arg.startsWith("--context_param")) {
            String keyValue = arg.substring(16);
            int index = -1;
            if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
                if (fatherPid==null) {
                    context_param.put(keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
                } else { // the subjob won't escape the especial chars
                    context_param.put(keyValue.substring(0, index), keyValue.substring(index + 1) );
                }
            }
        } else if (arg.startsWith("--log4jLevel=")) {
            log4jLevel = arg.substring(13);
		} else if (arg.startsWith("--monitoring") && arg.contains("=")) {//for trunjob call
		    final int equal = arg.indexOf('=');
			final String key = arg.substring("--".length(), equal);
			System.setProperty(key, arg.substring(equal + 1));
		}
    }
    
    private static final String NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY = "<TALEND_NULL>";

    private final String[][] escapeChars = {
        {"\\\\","\\"},{"\\n","\n"},{"\\'","\'"},{"\\r","\r"},
        {"\\f","\f"},{"\\b","\b"},{"\\t","\t"}
        };
    private String replaceEscapeChars (String keyValue) {

		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}

		StringBuilder result = new StringBuilder();
		int currIndex = 0;
		while (currIndex < keyValue.length()) {
			int index = -1;
			// judege if the left string includes escape chars
			for (String[] strArray : escapeChars) {
				index = keyValue.indexOf(strArray[0],currIndex);
				if (index>=0) {

					result.append(keyValue.substring(currIndex, index + strArray[0].length()).replace(strArray[0], strArray[1]));
					currIndex = index + strArray[0].length();
					break;
				}
			}
			// if the left string doesn't include escape chars, append the left into the result
			if (index < 0) {
				result.append(keyValue.substring(currIndex));
				currIndex = currIndex + keyValue.length();
			}
		}

		return result.toString();
    }

    public Integer getErrorCode() {
        return errorCode;
    }


    public String getStatus() {
        return status;
    }

    ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 *     73627 characters generated by Talend Open Studio for Big Data 
 *     on the 18 mai 2022 22:37:53 CEST
 ************************************************************************************************/